services:
  backend:
    build: ./backend
    restart: unless-stopped
    volumes:
      - /data/bookcompass/backend-data:/app/data

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
